version: '3.9'

services:
      
  wordpress_multisite_db:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: none
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ${PWD}/shared_fs/wp_db:/var/lib/mysql

  wordpress_multisite:
    build: https://github.com/AndreaDiPietro-ADP/wordpress-dockerfile-development-purpose.git#main
    deploy:
      restart_policy:
        condition: none
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: wordpress_multisite_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      XDEBUG_CONFIG: |
        xdebug.mode=debug,develop
        xdebug.client_host=host.docker.internal
        xdebug.client_port=9003
        xdebug.idekey="phpdebugkey"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
    volumes:
      - ${PWD}/shared_fs/wp_fs:/var/www/html

